/* tslint:disable */
/* eslint-disable */
/**
 * Social Voting Platform API (Team 7 - Final)
 * 카카오 로그인 도입 및 통계 기능이 제거된 최종 실전용 명세입니다. 6/7 마감을 목표로 백엔드 구현 난이도를 최소화하였습니다. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AuthKakaoPostRequest {
    /**
     * 카카오 SDK에서 발급받은 Access Token
     */
    'accessToken'?: string;
}
export interface Vote {
    'id'?: string;
    'title'?: string;
    /**
     * 투표 진행 상태
     */
    'status'?: VoteStatusEnum;
    'options'?: Array<VoteOption>;
}

export const VoteStatusEnum = {
    Open: 'open',
    Closed: 'closed',
} as const;

export type VoteStatusEnum = typeof VoteStatusEnum[keyof typeof VoteStatusEnum];

export interface VoteCreate {
    'title'?: string;
    'options'?: Array<VoteCreateOptionsInner>;
}
export interface VoteCreateOptionsInner {
    'name'?: string;
    'kakao_id'?: string;
    'lat'?: number;
    'lng'?: number;
}
export interface VoteOption {
    'id'?: string;
    'name'?: string;
    'kakao_id'?: string;
}
export interface VotesIdParticipatePostRequest {
    'optionId'?: string;
}
export interface VotesIdResultsGet200Response {
    'totalVotes'?: number;
    'options'?: Array<VotesIdResultsGet200ResponseOptionsInner>;
}
export interface VotesIdResultsGet200ResponseOptionsInner {
    'optionId'?: string;
    'name'?: string;
    'count'?: number;
}

/**
 * IdentificationApi - axios parameter creator
 */
export const IdentificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 카카오 토큰으로 서비스 로그인
         * @param {AuthKakaoPostRequest} authKakaoPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authKakaoPost: async (authKakaoPostRequest: AuthKakaoPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authKakaoPostRequest' is not null or undefined
            assertParamExists('authKakaoPost', 'authKakaoPostRequest', authKakaoPostRequest)
            const localVarPath = `/auth/kakao`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authKakaoPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IdentificationApi - functional programming interface
 */
export const IdentificationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IdentificationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 카카오 토큰으로 서비스 로그인
         * @param {AuthKakaoPostRequest} authKakaoPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authKakaoPost(authKakaoPostRequest: AuthKakaoPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authKakaoPost(authKakaoPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IdentificationApi.authKakaoPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IdentificationApi - factory interface
 */
export const IdentificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IdentificationApiFp(configuration)
    return {
        /**
         * 
         * @summary 카카오 토큰으로 서비스 로그인
         * @param {AuthKakaoPostRequest} authKakaoPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authKakaoPost(authKakaoPostRequest: AuthKakaoPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authKakaoPost(authKakaoPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IdentificationApi - object-oriented interface
 */
export class IdentificationApi extends BaseAPI {
    /**
     * 
     * @summary 카카오 토큰으로 서비스 로그인
     * @param {AuthKakaoPostRequest} authKakaoPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authKakaoPost(authKakaoPostRequest: AuthKakaoPostRequest, options?: RawAxiosRequestConfig) {
        return IdentificationApiFp(this.configuration).authKakaoPost(authKakaoPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VoteApi - axios parameter creator
 */
export const VoteApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 전체 투표 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        votesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/votes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 특정 투표에 참여 (인증 필요)
         * @param {string} id 
         * @param {VotesIdParticipatePostRequest} votesIdParticipatePostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        votesIdParticipatePost: async (id: string, votesIdParticipatePostRequest: VotesIdParticipatePostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('votesIdParticipatePost', 'id', id)
            // verify required parameter 'votesIdParticipatePostRequest' is not null or undefined
            assertParamExists('votesIdParticipatePost', 'votesIdParticipatePostRequest', votesIdParticipatePostRequest)
            const localVarPath = `/votes/{id}/participate`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(votesIdParticipatePostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 투표 결과(단순 득표수) 조회
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        votesIdResultsGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('votesIdResultsGet', 'id', id)
            const localVarPath = `/votes/{id}/results`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 신규 투표 생성 (인증 필요)
         * @param {VoteCreate} voteCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        votesPost: async (voteCreate: VoteCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'voteCreate' is not null or undefined
            assertParamExists('votesPost', 'voteCreate', voteCreate)
            const localVarPath = `/votes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(voteCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VoteApi - functional programming interface
 */
export const VoteApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VoteApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 전체 투표 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async votesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Vote>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.votesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoteApi.votesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 특정 투표에 참여 (인증 필요)
         * @param {string} id 
         * @param {VotesIdParticipatePostRequest} votesIdParticipatePostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async votesIdParticipatePost(id: string, votesIdParticipatePostRequest: VotesIdParticipatePostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.votesIdParticipatePost(id, votesIdParticipatePostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoteApi.votesIdParticipatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 투표 결과(단순 득표수) 조회
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async votesIdResultsGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VotesIdResultsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.votesIdResultsGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoteApi.votesIdResultsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 신규 투표 생성 (인증 필요)
         * @param {VoteCreate} voteCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async votesPost(voteCreate: VoteCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.votesPost(voteCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoteApi.votesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VoteApi - factory interface
 */
export const VoteApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VoteApiFp(configuration)
    return {
        /**
         * 
         * @summary 전체 투표 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        votesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Vote>> {
            return localVarFp.votesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 특정 투표에 참여 (인증 필요)
         * @param {string} id 
         * @param {VotesIdParticipatePostRequest} votesIdParticipatePostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        votesIdParticipatePost(id: string, votesIdParticipatePostRequest: VotesIdParticipatePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.votesIdParticipatePost(id, votesIdParticipatePostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 투표 결과(단순 득표수) 조회
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        votesIdResultsGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<VotesIdResultsGet200Response> {
            return localVarFp.votesIdResultsGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 신규 투표 생성 (인증 필요)
         * @param {VoteCreate} voteCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        votesPost(voteCreate: VoteCreate, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.votesPost(voteCreate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VoteApi - object-oriented interface
 */
export class VoteApi extends BaseAPI {
    /**
     * 
     * @summary 전체 투표 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public votesGet(options?: RawAxiosRequestConfig) {
        return VoteApiFp(this.configuration).votesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 특정 투표에 참여 (인증 필요)
     * @param {string} id 
     * @param {VotesIdParticipatePostRequest} votesIdParticipatePostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public votesIdParticipatePost(id: string, votesIdParticipatePostRequest: VotesIdParticipatePostRequest, options?: RawAxiosRequestConfig) {
        return VoteApiFp(this.configuration).votesIdParticipatePost(id, votesIdParticipatePostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 투표 결과(단순 득표수) 조회
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public votesIdResultsGet(id: string, options?: RawAxiosRequestConfig) {
        return VoteApiFp(this.configuration).votesIdResultsGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 신규 투표 생성 (인증 필요)
     * @param {VoteCreate} voteCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public votesPost(voteCreate: VoteCreate, options?: RawAxiosRequestConfig) {
        return VoteApiFp(this.configuration).votesPost(voteCreate, options).then((request) => request(this.axios, this.basePath));
    }
}



