name: Deploy API Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'specs/api/openapi.yaml'
      - 'specs/api/final_openapi.yaml'
  workflow_dispatch:

# 🔐 권한 명시 추가 (쓰기 권한 필요)
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Generate API Docs 📄
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html2
          openapi-file: specs/api/openapi.yaml
          output-dir: docs/api

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api
